
export const WHITE_CARDS = [
    "A big black dick",
    "A bigger, blacker dick",
    "The biggest, blackest dick",
    "A bleached asshole",
    "A brain tumor",
    "A bucket of fish heads",
    "A can of whoop-ass",
    "A cooler full of organs",
    "A death ray",
    "A defective condom",
    "A disappointed birthday clown",
    "A falcon with a cap on its head",
    "A fetid burp",
    "A foul mouth",
    "A gassy antelope",
    "A gentle caress of the inner thigh",
    "A good sniff",
    "A Gypsy curse",
    "A homoerotic volleyball montage",
    "A hot mess",
    "A lifetime of sadness",
    "A look-see",
    "A low standard of living",
    "A magic hippie love cloud",
    "A man on the brink of orgasm",
    "A mating display",
    "A micro-penis",
    "A middle-aged man on roller skates",
    "A mime having a stroke",
    "A monkey smoking a cigar",
    "A mopey zoo lion",
    "A murder most foul",
    "A pile of squirming bodies",
    "A rival dojo",
    "A robust mongoloid",
    "A sad handjob",
    "A salty surprise",
    "A sausage festival",
    "A sea of troubles",
    "A stray pube",
    "A supermassive black hole",
    "A thermonuclear detonation",
    "A time travel paradox",
    "A tiny horse",
    "A windmill full of corpses",
    "A zesty breakfast burrito",
    "Aaron Burr",
    "Active listening",
    "Actually taking candy from a baby",
    "Adderall™",
    "African children",
    "Agriculture",
    "AIDS",
    "Alcoholism",
    "All-you-can-eat shrimp for $4.99",
    "Altar boys",
    "American Gladiators",
    "Amputees",
    "An army of skeletons",
    "An asymmetric boob job",
    "An erection that lasts longer than four hours",
    "An honest cop with nothing left to lose",
    "An icepick lobotomy",
    "An M. Night Shyamalan plot twist",
    "An Oedipus complex",
    "An unhinged ferris wheel rolling toward the sea",
    "Anal beads",
    "Another goddamn vampire movie",
    "Apologizing",
    "Appreciative snapping",
    "Arnold Schwarzenegger",
    "Asians who aren't good at math",
    "Assless chaps",
    "Attitude",
    "Auschwitz",
    "Authentic Mexican cuisine",
    "Autocannibalism",
    "AXE Body Spray",
    "Balls",
    "Barack Obama",
    "Basic human decency",
    "Batman",
    "Beating your wives",
    "Beefin' over turf",
    "Bees?",
    "Being a dick to children",
    "Being a motherfucking sorcerer",
    "Being a woman",
    "Being fabulous",
    "Being marginalized",
    "Being on fire",
    "Being rich",
    "Bill Nye the Science Guy",
    "Bingeing and purging",
    "Bitches",
    "Black people",
    "Bling",
    "Booby-trapping the house to foil burglars",
    "Boogers",
    "Boris the Soviet Love Hammer",
    "Bosnian chicken farmers",
    "Breaking out into song and dance",
    "Britney Spears at 55",
    "Bullshit",
    "Cards Against Humanity",
    "Carne asada",
    "Catapults",
    "Centaurs",
    "Chainsaws for hands",
    "Charisma",
    "Cheating in the Special Olympics",
    "Child abuse",
    "Child beauty pageants",
    "Children on leashes",
    "Chivalry",
    "Christopher Walken",
    "Civilian casualties",
    "Clams",
    "Classist undertones",
    "Cleaning out your pipes",
    "Coat hanger abortions",
    "Cockfights",
    "College",
    "Concealing a boner",
    "Consultants",
    "Copping a feel",
    "Coughing into a vagina",
    "Count Chocula",
    "Crippling debt",
    "Crystal meth",
    "Cuddling",
    "Customer service representatives",
    "Cybernetic enhancements",
    "Daddy issues",
    "Daddy's belt",
    "Dancing with a broom",
    "Darth Vader",
    "Date rape",
    "Dead babies",
    "Dead parents",
    "Death by Pizza",
    "Dental dams",
    "Dick fingers",
    "Dining with cardboard cutouts of the cast of Friends",
    "Doin' it in the butt",
    "Doing the right thing",
    "Domino's™ Oreo™ Dessert Pizza",
    "Doritos and a Fruit Roll-Up",
    "Double penetration",
    "Drinking alone",
    "Dropping a chandelier on your enemies and riding the rope up",
    "Dry heaving",
    "Dwarf tossing",
    "Dying of dysentery",
    "Dying",
    "Eating all of the cookies before the AIDS bake-sale",
    "Eating an albino",
    "Eating an entire snowman",
    "Eating the last known bison",
    "Edible underpants",
    "Elderly Japanese men",
    "Elf cum",
    "Embryonic stem cells",
    "Emergency medical personnel",
    "Emotions",
    "Enormous Scandinavian women",
    "Erectile dysfunction",
    "Estrogen",
    "Ethnic cleansing",
    "Eugenics",
    "Euphoria™ by Calvin Klein",
    "Exactly what you'd expect",
    "Exchanging pleasantries",
    "Existing",
    "Expecting a burp and vomiting on the floor",
    "Explosions",
    "Fabricating complicated lies",
    "Famine",
    "Fancy Feast®",
    "Farting and walking away",
    "Fear itself",
    "Feeding Rosie O'Donnell",
    "Fetal alcohol syndrome",
    "Fiery poops",
    "Figgy pudding",
    "Finding a skeleton",
    "Finding Waldo",
    "Finger painting",
    "Fingering",
    "Firing a rifle into the air while balls deep in a squealing hog",
    "Five-Dollar Footlongs™",
    "Flash flooding",
    "Flesh-eating bacteria",
    "Flightless birds",
    "Flying sex snakes",
    "Foreskin",
    "Forgetting the Alamo",
    "Former President George W. Bush",
    "Free samples",
    "Friction",
    "Friendly fire",
    "Friends with benefits",
    "Frolicking",
    "Fuck Mountain",
    "Fucking up 'Silent Night' in front of 300 parents",
    "Full frontal nudity",
    "Gandalf",
    "Geese",
    "Genetically engineered super-soldiers",
    "Genghis Khan",
    "Genital piercings",
    "George Clooney's musk",
    "German dungeon porn",
    "Getting drunk on mouthwash",
    "Getting hilariously gang-banged by the Blue Man Group",
    "Getting in her pants, politely",
    "Getting naked and watching Nickelodeon",
    "Getting really high",
    "Getting so angry that you pop a boner",
    "Ghosts",
    "Girls who shouldn't go wild",
    "Giving 110%",
    "Gladys Knight and the Pips",
    "Global warming",
    "Gloryholes",
    "Goats eating cans",
    "Goblins",
    "God",
    "GoGurt®",
    "Golden showers",
    "Good grammar",
    "Grandma",
    "Grandpa's ashes",
    "Graphic violence, adult language, and some sexual content",
    "Grave robbing",
    "Guys who don't call",
    "Half-assed foreplay",
    "Harry Potter erotica",
    "Heartwarming orphans",
    "Her Royal Highness, Queen Elizabeth II",
    "Heteronormativity",
    "Hillary Clinton",
    "Hipsters",
    "Historical revisionism",
    "Historically black colleges",
    "Home video of Oprah sobbing into a Lean Cuisine®",
    "Homeless people",
    "Hope",
    "Hormone injections",
    "Horrifying laser hair removal accidents",
    "Horse meat",
    "Hot cheese",
    "Hot Pockets®",
    "Hot people",
    "Hulk Hogan",
    "Hurricane Katrina",
    "Inappropriate yodeling",
    "Incest",
    "Insatiable bloodlust",
    "Intelligent design",
    "Invading Poland",
    "Italians",
    "Jaden Smith",
    "Jehovah's Witnesses",
    "Jennifer Lawrence",
    "Jerking off into a pool of children's tears",
    "Jew-fros",
    "Jewish fraternities",
    "Jiggling",
    "Jobless Southern men",
    "Joe Biden",
    "John Wilkes Booth",
    "Judge Judy",
    "Just the tip",
    "Justin Bieber",
    "Kamikaze pilots",
    "Kanye West",
    "Keanu Reeves",
    "Keg stands",
    "Kids with ass cancer",
    "Kim Jong-un",
    "Kissing the elderly",
    "Kittens!",
    "Lactation",
    "Lady Gaga",
    "Lance Armstrong's missing testicle",
    "Land mines",
    "Laying an egg",
    "Leaving an awkward voicemail",
    "Leprosy",
    "Leveling up",
    "Licking things to claim them as your own",
    "Listening to her problems",
    "Little boy penises",
    "Lockjaw",
    "Loose lips",
    "Lumberjack fantasies",
    "Lunchables™",
    "Lyin' Ted Cruz",
    "Mad cow disease",
    "Magnets",
    "Making a pouty face",
    "Making the penises kiss",
    "Makeup",
    "Man meat",
    "Mansplaining",
    "Masturbation",
    "Mathletes",
    "MechaHitler",
    "Media coverage",
    "Medieval Times® Dinner & Tournament",
    "Men",
    "Menstruation",
    "Michael Jackson",
    "Michelle Obama's arms",
    "Mild autism",
    "Mooing",
    "Moral ambiguity",
    "Morgan Freeman's voice",
    "Mouth herpes",
    "Mr. Clean, right behind you",
    "Muhammad (Praise Be Unto Him)",
    "Multiple stab wounds",
    "Mutually-assured destruction",
    "My collection of high-tech sex toys",
    "My first kill",
    "My genitals",
    "My humps",
    "My inner demons",
    "My little horses",
    "My machete",
    "My relationship status",
    "My sex life",
    "My soul",
    "My vagina",
    "Natalie Portman",
    "Natural male enhancement",
    "Natural selection",
    "Nazis",
    "Necrophilia",
    "Neil Patrick Harris",
    "New Age music",
    "Nicolas Cage",
    "Nipple blades",
    "Nocturnal emissions",
    "Not giving a shit about the Third World",
    "Not reciprocated oral sex",
    "Nothing",
    "Nuclear launch codes",
    "Obesity",
    "Object permanence",
    "Old-people smell",
    "Ominous background music",
    "One titty hanging out",
    "One trillion dollars",
    "Oopa-Loompas",
    "Opposable thumbs",
    "Overcompensation",
    "Pabst Blue Ribbon",
    "Pac-Man uncontrollably guzzling cum",
    "Panda sex",
    "Participating",
    "Parting the Red Sea",
    "Party poopers",
    "Passable transvestites",
    "Passing a kidney stone",
    "Passive-aggressive Post-it notes",
    "Pedophiles",
    "Peeing a little bit",
    "Penis envy",
    "Picking the wrong switch",
    "Pictures of boobs",
    "Pimp lope",
    "Pixelated bukkake",
    "Police brutality",
    "Pooping back and forth. Forever",
    "Poor life choices",
    "Poor people",
    "Poorly-timed Holocaust jokes",
    "Porn stars",
    "Powerful thighs",
    "Prancing",
    "Praying the gay away",
    "Preteens",
    "Pretending to care",
    "Prison rape",
    "Private parts",
    "Promising a cake",
    "Puberty",
    "Public ridicule",
    "Pulling out",
    "Pumping out a baby every nine months",
    "Puppies!",
    "Queefing",
    "Racially-biased standardized testing",
    "Radioactive Nazis",
    "Raping and pillaging",
    "Re-gifting",
    "Repression",
    "Republicans",
    "Revenge fucking",
    "Riding off into the sunset",
    "Ripped cheese",
    "Road head",
    "Robert Downey Jr",
    "RoboCop",
    "Rohypnol",
    "Roofies",
    "Running out of semen",
    "Rush Limbaugh's soft, shitty body",
    "Same-sex ice dancing",
    "Santa Claus",
    "Sarah Palin",
    "Saxophone solos",
    "Scalping",
    "Science",
    "Scientology",
    "Scrubbing under the folds",
    "Sean Connery",
    "Sean Penn",
    "Seduction",
    "Self-loathing",
    "Seppuku",
    "Serfdom",
    "Seven dead bodies in the trunk",
    "Sex with animals",
    "Sex with Patrick Stewart",
    "Sexting",
    "Sexual humiliation",
    "Sexual tension",
    "Sexy pillow fights",
    "Shapeshifters",
    "Shaquille O'Neal's acting career",
    "Sharing needles",
    "Skeletor",
    "Slapping a racist old lady",
    "Slow motion",
    "Smallpox blankets",
    "Smegma",
    "Sniffing glue",
    "Socks",
    "Soiling oneself",
    "Some god damn peace and quiet",
    "Soup that is too hot",
    "Spaghetti? Again?",
    "Spectacular abs",
    "Spending lots of money",
    "Sperm whales",
    "Spontaneous human combustion",
    "Spring break!",
    "Statistically validated stereotypes",
    "Stephen Hawking talking dirty",
    "Stifling a giggle at the mention of Hutus and Tutsis",
    "Stranger danger",
    "Subduing a grizzly bear and making her your wife",
    "Sudden Poop Explosion Disease",
    "Suicidal thoughts",
    "Sunshine and rainbows",
    "Surprise sex!",
    "Survivor's guilt",
    "Sweet, sweet vengeance",
    "Swiftly achieving orgasm",
    "Switching to Geico®",
    "Swooping",
    "Take-backsies",
    "Taking a man's eyes and balls out and putting his eyes where his balls go and then his balls in the eye holes",
    "Taking off your shirt",
    "Tangled Slinkys",
    "Tasteful sideboob",
    "Teaching a robot to love",
    "Team-building exercises",
    "Teenage pregnancy",
    "Tentacle porn",
    "Testicular torsion",
    "That ass",
    "That thing that electrocutes your abs",
    "The American Dream",
    "The Amish",
    "The arrival of the pizza",
    "The Babe",
    "The Big Bang",
    "The Blood of Christ",
    "The Boy Scouts of America",
    "The Care Bear Stare",
    "The Chinese gymnastics team",
    "The chronic",
    "The clitoris",
    "The Dance of the Sugar Plum Fairy",
    "The day the birds attacked",
    "The Donald Trump Seal of Approval™",
    "The economy",
    "The end of days",
    "The Fanta® girls",
    "The Force",
    "The gays",
    "The glass ceiling",
    "The Google",
    "The Gulags",
    "The Hamburglar",
    "The hardworking Mexican",
    "The harsh light of day",
    "The heart of a child",
    "The hiccups",
    "The Holy Bible",
    "The homosexual agenda",
    "The human body",
    "The Hustle",
    "The inevitable heat death of the universe",
    "The invisible hand",
    "The Jews",
    "The KKK",
    "The Kool-Aid Man",
    "The Little Engine That Could",
    "The Make-A-Wish® Foundation",
    "The milk man",
    "The miracle of childbirth",
    "The mixing of the races",
    "The new Radiohead album",
    "The placenta",
    "The Pope",
    "The profoundly handicapped",
    "The Rapture",
    "The Rev. Dr. Martin Luther King, Jr",
    "The shambling corpse of Larry King",
    "The South",
    "The Star Wars Holiday Special",
    "The systematic destruction of an entire people and their way of life",
    "The Tempur-Pedic® Swedish Sleep System™",
    "The terrorists",
    "The Three-Fifths compromise",
    "The tiny calloused hands of the Chinese children that made this card",
    "The token minority",
    "The Trail of Tears",
    "The true meaning of Christmas",
    "The Übermensch",
    "The Underground Railroad",
    "The violation of our most basic human rights",
    "The Virginia Tech Massacre",
    "The World of Warcraft",
    "Third base",
    "Tiny nipples",
    "Tom Cruise",
    "Tongue",
    "Toni Morrison's vagina",
    "Too much hair gel",
    "Tripping balls",
    "Two midgets shitting into a bucket",
    "Unfathomable stupidity",
    "Used panties",
    "Vegetarianism",
    "Vehicular manslaughter",
    "Viagra®",
    "Vigilante justice",
    "Vigorous jazz hands",
    "Vikings",
    "Waiting 'til marriage",
    "Waking up half-naked in a Denny's parking lot",
    "Waterboarding",
    "Weapons-grade plutonium",
    "Wearing underwear inside-out to avoid doing laundry",
    "When you fart and a little bit comes out",
    "Whining like a little bitch",
    "Whipping it out",
    "White people",
    "White privilege",
    "Wifely duties",
    "William Shatner",
    "Winking at old people",
    "Wiping her butt",
    "Women in yogurt commercials",
    "Women's suffrage",
    "Words, words, words",
    "World peace",
    "Yeast",
    "YOU MUST CONSTRUCT ADDITIONAL PYLONS",
    "Your mom",
    "Getting railed by a horse",
    "Getting railed by the entire defensive line",
    "Getting railed by Santa Claus",
    "Getting railed by your mom",
    "Being balls deep in a squealing hog",
    "Fucking a goat",
    "My massive collection of dildos",
    "Slapping a bitch",
    "Eating ass",
    "Cumming so hard you pass out",
    "Shitting in a bucket",
    "Getting caught masturbating",
    "A soup sandwich",
    "My useless degree",
    "Crippling depression",
    "Throwing a virgin into a volcano",
    "Sacrificing a goat",
    "Drinking bong water",
    "Vomiting in a handbag",
    "Getting a blowjob from a grandmother",
    "Fisting",
    "A bag of magic beans",
    "A bitch slap",
    "A botched circumcision",
    "A bucket of fish heads",
    "A can of whoop-ass",
    "A cooler full of organs",
    "A death ray",
    "A defective condom",
    "A disappointed birthday clown",
    "A falcon with a cap on its head",
    "A fetid burp",
    "A foul mouth",
    "A gassy antelope",
    "A gentle caress of the inner thigh",
    "A good sniff",
    "A Gypsy curse",
    "A homoerotic volleyball montage",
    "A hot mess",
    "A lifetime of sadness",
    "A look-see",
    "A low standard of living",
    "A magic hippie love cloud",
    "A man on the brink of orgasm",
    "A mating display",
    "A micro-penis",
    "A middle-aged man on roller skates",
    "A mime having a stroke",
    "A monkey smoking a cigar",
    "A mopey zoo lion",
    "A murder most foul",
    "A pile of squirming bodies",
    "A rival dojo",
    "A robust mongoloid",
    "A sad handjob",
    "A salty surprise",
    "A sausage festival",
    "A sea of troubles",
    "A stray pube",
    "A supermassive black hole",
    "A thermonuclear detonation",
    "A time travel paradox",
    "A tiny horse",
    "A windmill full of corpses",
    "A zesty breakfast burrito",
    "Aaron Burr",
    "Active listening",
    "Actually taking candy from a baby",
    "Adderall™",
    "African children",
    "Agriculture",
    "AIDS",
    "Alcoholism",
    "All-you-can-eat shrimp for $4.99",
    "Altar boys",
    "American Gladiators",
    "Amputees",
    "An army of skeletons",
    "An asymmetric boob job",
    "An erection that lasts longer than four hours",
    "An honest cop with nothing left to lose",
    "An icepick lobotomy",
    "An M. Night Shyamalan plot twist",
    "An Oedipus complex",
    "An unhinged ferris wheel rolling toward the sea",
    "Anal beads",
    "Another goddamn vampire movie",
    "Apologizing",
    "Appreciative snapping",
    "Arnold Schwarzenegger",
    "Asians who aren't good at math",
    "Assless chaps",
    "Attitude",
    "Auschwitz",
    "Authentic Mexican cuisine",
    "Autocannibalism",
    "AXE Body Spray",
    "Balls",
    "Barack Obama",
    "Basic human decency",
    "Batman",
    "Beating your wives",
    "Beefin' over turf",
    "Bees?",
    "Being a dick to children",
    "Being a motherfucking sorcerer",
    "Being a woman",
    "Being fabulous",
    "Being marginalized",
    "Being on fire",
    "Being rich",
    "Bill Nye the Science Guy",
    "Bingeing and purging",
    "Bitches",
    "Black people",
    "Bling",
    "Booby-trapping the house to foil burglars",
    "Boogers",
    "Boris the Soviet Love Hammer",
    "Bosnian chicken farmers",
    "Breaking out into song and dance",
    "Britney Spears at 55",
    "Bullshit",
    "Cards Against Humanity",
    "Carne asada",
    "Catapults",
    "Centaurs",
    "Chainsaws for hands",
    "Charisma",
    "Cheating in the Special Olympics",
    "Child abuse",
    "Child beauty pageants",
    "Children on leashes",
    "Chivalry",
    "Christopher Walken",
    "Civilian casualties",
    "Clams",
    "Classist undertones",
    "Cleaning out your pipes",
    "Coat hanger abortions",
    "Cockfights",
    "College",
    "Concealing a boner",
    "Consultants",
    "Copping a feel",
    "Coughing into a vagina",
    "Count Chocula",
    "Crippling debt",
    "Crystal meth",
    "Cuddling",
    "Customer service representatives",
    "Cybernetic enhancements",
    "Daddy issues",
    "Daddy's belt",
    "Dancing with a broom",
    "Darth Vader",
    "Date rape",
    "Dead babies",
    "Dead parents",
    "Death by Pizza",
    "Dental dams",
    "Dick fingers",
    "Dining with cardboard cutouts of the cast of Friends",
    "Doin' it in the butt",
    "Doing the right thing",
    "Domino's™ Oreo™ Dessert Pizza",
    "Doritos and a Fruit Roll-Up",
    "Double penetration",
    "Drinking alone",
    "Dropping a chandelier on your enemies and riding the rope up",
    "Dry heaving",
    "Dwarf tossing",
    "Dying of dysentery",
    "Dying",
    "Eating all of the cookies before the AIDS bake-sale",
    "Eating an albino",
    "Eating an entire snowman",
    "Eating the last known bison",
    "Edible underpants",
    "Elderly Japanese men",
    "Elf cum",
    "Embryonic stem cells",
    "Emergency medical personnel",
    "Emotions",
    "Enormous Scandinavian women",
    "Erectile dysfunction",
    "Estrogen",
    "Ethnic cleansing",
    "Eugenics",
    "Euphoria™ by Calvin Klein",
    "Exactly what you'd expect",
    "Exchanging pleasantries",
    "Existing",
    "Expecting a burp and vomiting on the floor",
    "Explosions",
    "Fabricating complicated lies",
    "Famine",
    "Fancy Feast®",
    "Farting and walking away",
    "Fear itself",
    "Feeding Rosie O'Donnell",
    "Fetal alcohol syndrome",
    "Fiery poops",
    "Figgy pudding",
    "Finding a skeleton",
    "Finding Waldo",
    "Finger painting",
    "Fingering",
    "Firing a rifle into the air while balls deep in a squealing hog",
    "Five-Dollar Footlongs™",
    "Flash flooding",
    "Flesh-eating bacteria",
    "Flightless birds",
    "Flying sex snakes",
    "Foreskin",
    "Forgetting the Alamo",
    "Former President George W. Bush",
    "Free samples",
    "Friction",
    "Friendly fire",
    "Friends with benefits",
    "Frolicking",
    "Fuck Mountain",
    "Fucking up 'Silent Night' in front of 300 parents",
    "Full frontal nudity",
    "Gandalf",
    "Geese",
    "Genetically engineered super-soldiers",
    "Genghis Khan",
    "Genital piercings",
    "George Clooney's musk",
    "German dungeon porn",
    "Getting drunk on mouthwash",
    "Getting hilariously gang-banged by the Blue Man Group",
    "Getting in her pants, politely",
    "Getting naked and watching Nickelodeon",
    "Getting really high",
    "Getting so angry that you pop a boner",
    "Ghosts",
    "Girls who shouldn't go wild",
    "Giving 110%",
    "Gladys Knight and the Pips",
    "Global warming",
    "Gloryholes",
    "Goats eating cans",
    "Goblins",
    "God",
    "GoGurt®",
    "Golden showers",
    "Good grammar",
    "Grandma",
    "Grandpa's ashes",
    "Graphic violence, adult language, and some sexual content",
    "Grave robbing",
    "Guys who don't call",
    "Half-assed foreplay",
    "Harry Potter erotica",
    "Heartwarming orphans",
    "Her Royal Highness, Queen Elizabeth II",
    "Heteronormativity",
    "Hillary Clinton",
    "Hipsters",
    "Historical revisionism",
    "Historically black colleges",
    "Home video of Oprah sobbing into a Lean Cuisine®",
    "Homeless people",
    "Hope",
    "Hormone injections",
    "Horrifying laser hair removal accidents",
    "Horse meat",
    "Hot cheese",
    "Hot Pockets®",
    "Hot people",
    "Hulk Hogan",
    "Hurricane Katrina",
    "Inappropriate yodeling",
    "Incest",
    "Insatiable bloodlust",
    "Intelligent design",
    "Invading Poland",
    "Italians",
    "Jaden Smith",
    "Jehovah's Witnesses",
    "Jennifer Lawrence",
    "Jerking off into a pool of children's tears",
    "Jew-fros",
    "Jewish fraternities",
    "Jiggling",
    "Jobless Southern men",
    "Joe Biden",
    "John Wilkes Booth",
    "Judge Judy",
    "Just the tip",
    "Justin Bieber",
    "Kamikaze pilots",
    "Kanye West",
    "Keanu Reeves",
    "Keg stands",
    "Kids with ass cancer",
    "Kim Jong-un",
    "Kissing the elderly",
    "Kittens!",
    "Lactation",
    "Lady Gaga",
    "Lance Armstrong's missing testicle",
    "Land mines",
    "Laying an egg",
    "Leaving an awkward voicemail",
    "Leprosy",
    "Leveling up",
    "Licking things to claim them as your own",
    "Listening to her problems",
    "Little boy penises",
    "Lockjaw",
    "Loose lips",
    "Lumberjack fantasies",
    "Lunchables™",
    "Lyin' Ted Cruz",
    "Mad cow disease",
    "Magnets",
    "Making a pouty face",
    "Making the penises kiss",
    "Makeup",
    "Man meat",
    "Mansplaining",
    "Masturbation",
    "Mathletes",
    "MechaHitler",
    "Media coverage",
    "Medieval Times® Dinner & Tournament",
    "Men",
    "Menstruation",
    "Michael Jackson",
    "Michelle Obama's arms",
    "Mild autism",
    "Mooing",
    "Moral ambiguity",
    "Morgan Freeman's voice",
    "Mouth herpes",
    "Mr. Clean, right behind you",
    "Muhammad (Praise Be Unto Him)",
    "Multiple stab wounds",
    "Mutually-assured destruction",
    "My collection of high-tech sex toys",
    "My first kill",
    "My genitals",
    "My humps",
    "My inner demons",
    "My little horses",
    "My machete",
    "My relationship status",
    "My sex life",
    "My soul",
    "My vagina",
    "Natalie Portman",
    "Natural male enhancement",
    "Natural selection",
    "Nazis",
    "Necrophilia",
    "Neil Patrick Harris",
    "New Age music",
    "Nicolas Cage",
    "Nipple blades",
    "Nocturnal emissions",
    "Not giving a shit about the Third World",
    "Not reciprocated oral sex",
    "Nothing",
    "Nuclear launch codes",
    "Obesity",
    "Object permanence",
    "Old-people smell",
    "Ominous background music",
    "One titty hanging out",
    "One trillion dollars",
    "Oopa-Loompas",
    "Opposable thumbs",
    "Overcompensation",
    "Pabst Blue Ribbon",
    "Pac-Man uncontrollably guzzling cum",
    "Panda sex",
    "Participating",
    "Parting the Red Sea",
    "Party poopers",
    "Passable transvestites",
    "Passing a kidney stone",
    "Passive-aggressive Post-it notes",
    "Pedophiles",
    "Peeing a little bit",
    "Penis envy",
    "Picking the wrong switch",
    "Pictures of boobs",
    "Pimp lope",
    "Pixelated bukkake",
    "Police brutality",
    "Pooping back and forth. Forever",
    "Poor life choices",
    "Poor people",
    "Poorly-timed Holocaust jokes",
    "Porn stars",
    "Powerful thighs",
    "Prancing",
    "Praying the gay away",
    "Preteens",
    "Pretending to care",
    "Prison rape",
    "Private parts",
    "Promising a cake",
    "Puberty",
    "Public ridicule",
    "Pulling out",
    "Pumping out a baby every nine months",
    "Puppies!",
    "Queefing",
    "Racially-biased standardized testing",
    "Radioactive Nazis",
    "Raping and pillaging",
    "Re-gifting",
    "Repression",
    "Republicans",
    "Revenge fucking",
    "Riding off into the sunset",
    "Ripped cheese",
    "Road head",
    "Robert Downey Jr",
    "RoboCop",
    "Rohypnol",
    "Roofies",
    "Running out of semen",
    "Rush Limbaugh's soft, shitty body",
    "Same-sex ice dancing",
    "Santa Claus",
    "Sarah Palin",
    "Saxophone solos",
    "Scalping",
    "Science",
    "Scientology",
    "Scrubbing under the folds",
    "Sean Connery",
    "Sean Penn",
    "Seduction",
    "Self-loathing",
    "Seppuku",
    "Serfdom",
    "Seven dead bodies in the trunk",
    "Sex with animals",
    "Sex with Patrick Stewart",
    "Sexting",
    "Sexual humiliation",
    "Sexual tension",
    "Sexy pillow fights",
    "Shapeshifters",
    "Shaquille O'Neal's acting career",
    "Sharing needles",
    "Skeletor",
    "Slapping a racist old lady",
    "Slow motion",
    "Smallpox blankets",
    "Smegma",
    "Sniffing glue",
    "Socks",
    "Soiling oneself",
    "Some god damn peace and quiet",
    "Soup that is too hot",
    "Spaghetti? Again?",
    "Spectacular abs",
    "Spending lots of money",
    "Sperm whales",
    "Spontaneous human combustion",
    "Spring break!",
    "Statistically validated stereotypes",
    "Stephen Hawking talking dirty",
    "Stifling a giggle at the mention of Hutus and Tutsis",
    "Stranger danger",
    "Subduing a grizzly bear and making her your wife",
    "Sudden Poop Explosion Disease",
    "Suicidal thoughts",
    "Sunshine and rainbows",
    "Surprise sex!",
    "Survivor's guilt",
    "Sweet, sweet vengeance",
    "Swiftly achieving orgasm",
    "Switching to Geico®",
    "Swooping",
    "Take-backsies",
    "Taking a man's eyes and balls out and putting his eyes where his balls go and then his balls in the eye holes",
    "Taking off your shirt",
    "Tangled Slinkys",
    "Tasteful sideboob",
    "Teaching a robot to love",
    "Team-building exercises",
    "Teenage pregnancy",
    "Tentacle porn",
    "Testicular torsion",
    "That ass",
    "That thing that electrocutes your abs",
    "The American Dream",
    "The Amish",
    "The arrival of the pizza",
    "The Babe",
    "The Big Bang",
    "The Blood of Christ",
    "The Boy Scouts of America",
    "The Care Bear Stare",
    "The Chinese gymnastics team",
    "The chronic",
    "The clitoris",
    "The Dance of the Sugar Plum Fairy",
    "The day the birds attacked",
    "The Donald Trump Seal of Approval™",
    "The economy",
    "The end of days",
    "The Fanta® girls",
    "The Force",
    "The gays",
    "The glass ceiling",
    "The Google",
    "The Gulags",
    "The Hamburglar",
    "The hardworking Mexican",
    "The harsh light of day",
    "The heart of a child",
    "The hiccups",
    "The Holy Bible",
    "The homosexual agenda",
    "The human body",
    "The Hustle",
    "The inevitable heat death of the universe",
    "The invisible hand",
    "The Jews",
    "The KKK",
    "The Kool-Aid Man",
    "The Little Engine That Could",
    "The Make-A-Wish® Foundation",
    "The milk man",
    "The miracle of childbirth",
    "The mixing of the races",
    "The new Radiohead album",
    "The placenta",
    "The Pope",
    "The profoundly handicapped",
    "The Rapture",
    "The Rev. Dr. Martin Luther King, Jr",
    "The shambling corpse of Larry King",
    "The South",
    "The Star Wars Holiday Special",
    "The systematic destruction of an entire people and their way of life",
    "The Tempur-Pedic® Swedish Sleep System™",
    "The terrorists",
    "The Three-Fifths compromise",
    "The tiny calloused hands of the Chinese children that made this card",
    "The token minority",
    "The Trail of Tears",
    "The true meaning of Christmas",
    "The Übermensch",
    "The Underground Railroad",
    "The violation of our most basic human rights",
    "The Virginia Tech Massacre",
    "The World of Warcraft",
    "Third base",
    "Tiny nipples",
    "Tom Cruise",
    "Tongue",
    "Toni Morrison's vagina",
    "Too much hair gel",
    "Tripping balls",
    "Two midgets shitting into a bucket",
    "Unfathomable stupidity",
    "Used panties",
    "Vegetarianism",
    "Vehicular manslaughter",
    "Viagra®",
    "Vigilante justice",
    "Vigorous jazz hands",
    "Vikings",
    "Waiting 'til marriage",
    "Waking up half-naked in a Denny's parking lot",
    "Waterboarding",
    "Weapons-grade plutonium",
    "Wearing underwear inside-out to avoid doing laundry",
    "When you fart and a little bit comes out",
    "Whining like a little bitch",
    "Whipping it out",
    "White people",
    "White privilege",
    "Wifely duties",
    "William Shatner",
    "Winking at old people",
    "Wiping her butt",
    "Women in yogurt commercials",
    "Women's suffrage",
    "Words, words, words",
    "World peace",
    "Yeast",
    "YOU MUST CONSTRUCT ADDITIONAL PYLONS",
    // New cards (40 additional)
    "An existential crisis at 3 AM",
    "Forgetting how to walk",
    "A suspicious amount of garlic",
    "Writing fanfiction about your boss",
    "Aggressively sipping tea",
    "The wrong hole",
    "A deranged chihuahua",
    "Crying in the McDonald's parking lot",
    "Making eye contact while eating a banana",
    "Sending unsolicited feet pics",
    "A surprisingly violent Roomba",
    "Your FBI agent watching through your webcam",
    "Weaponized incompetence",
    "Eating cereal with water",
    "The audacity of this bitch",
    "Getting ghosted by your therapist",
    "A haunted sex doll",
    "LinkedIn influencers",
    "Your WiFi going out during a Zoom call",
    "Screaming into the void",
    "A taco that fights back",
    "Chaotic bisexual energy",
    "Uninstalling life",
    "The intrusive thoughts winning",
    "A feral child raised by TikTok",
    "Making PowerPoints about your trauma",
    "Watching Netflix on your ex's account",
    "Being the main character syndrome",
    "A very disappointed Duolingo owl",
    "Aggressive cuddling",
    "Microwaving fish in the office",
    "Daddy issues but make it fashion",
    "Your sleep paralysis demon",
    "Putting pineapple on pizza ironically",
    "Getting canceled on Twitter",
    "Thirst trapping for Jesus",
    "Yelling at pigeons to assert dominance",
    "The urge to commit arson",
    "Accidentally liking a photo from 2014",
    "Flint, Michigan",
    "Layette Rus",
    "Thong Wong",
    "Chris Pratt",
    "Bruno Mars",
    "Bonnie Blue",
    "The Smurfs",
    "Gay Midget Porn",
    "Dolphin Sex",
    "Charlie Kirk",
    "A furry suit",
    "A Black Hole",
    "Carrying the flame",
    "Sheep Balls",
];

export const BLACK_CARDS = [
    { text: "Why can't I sleep at night?", pick: 1 },
    { text: "I got 99 problems but _ ain't one.", pick: 1 },
    { text: "What's a girl's best friend?", pick: 1 },
    { text: "What's that smell?", pick: 1 },
    { text: "This is the way the world ends. Not with a bang but with _.", pick: 1 },
    { text: "What is Batman's guilty pleasure?", pick: 1 },
    { text: "TSA guidelines now prohibit _ on airplanes.", pick: 1 },
    { text: "What ended my last relationship?", pick: 1 },
    { text: "MTV's new reality show features eight washed-up celebrities living with _.", pick: 1 },
    { text: "I drink to forget _.", pick: 1 },
    { text: "I'm sorry, Professor, but I couldn't complete my homework because of _.", pick: 1 },
    { text: "Alternative medicine is now embracing the curative powers of _.", pick: 1 },
    { text: "What's the next Happy Meal® toy?", pick: 1 },
    { text: "It's a pity that kids these days are all getting involved with _.", pick: 1 },
    { text: "In the new Disney Channel Original Movie, Hannah Montana struggles with _ for the first time.", pick: 1 },
    { text: "_. That's how I want to die.", pick: 1 },
    { text: "What does Dick Cheney prefer?", pick: 1 },
    { text: "What's the most emo?", pick: 1 },
    { text: "Instead of coal, Santa now gives the bad children _.", pick: 1 },
    { text: "Next from J.K. Rowling: Harry Potter and the Chamber of _.", pick: 1 },
    { text: "A romantic, candlelit dinner would be incomplete without _.", pick: 1 },
    { text: "White people like _.", pick: 1 },
    { text: "_. Betcha can't have just one!", pick: 1 },
    { text: "War! What is it good for?", pick: 1 },
    { text: "BILLY MAYS HERE FOR _.", pick: 1 },
    { text: "_. High five, bro.", pick: 1 },
    { text: "During sex, I like to think about _.", pick: 1 },
    { text: "What did I bring back from Mexico?", pick: 1 },
    { text: "Boys have a penis, girls have a vagina, and like _.", pick: 1 },
    { text: "What are my parents hiding from me?", pick: 1 },
    { text: "What will always get you laid?", pick: 1 },
    { text: "What would grandma find disturbing, yet oddly charming?", pick: 1 },
    { text: "What did the US airdrop to the children of Afghanistan?", pick: 1 },
    { text: "What helps Obama sleep at night?", pick: 1 },
    { text: "Coming to Broadway this season, _: The Musical.", pick: 1 },
    { text: "When I am a billionaire, I shall erect a 50-foot statue to commemorate _.", pick: 1 },
    { text: "But before I kill you, Mr. Bond, I must show you _.", pick: 1 },
    { text: "What gives me uncontrollable gas?", pick: 1 },
    { text: "What do old people smell like?", pick: 1 },
    { text: "The class field trip was completely ruined by _.", pick: 1 },
    { text: "When Pharaoh remained unmoved, Moses called down a Plague of _.", pick: 1 },
    { text: "What's the new fad diet?", pick: 1 },
    { text: "What's my secret power?", pick: 1 },
    { text: "What's there a ton of in heaven?", pick: 1 },
    { text: "What would I do for a Klondike Bar?", pick: 1 },
    { text: "Daddy, why is mommy crying?", pick: 1 },
    { text: "What brought the orgy to a grinding halt?", pick: 1 },
    { text: "When I am President of the United States, I will create the Department of _.", pick: 1 },
    { text: "When I am President, I will create the Department of _.", pick: 1 },
    { text: "What's the crustiest?", pick: 1 },
    { text: "What did Vin Diesel eat for dinner?", pick: 1 },
    { text: "Why am I sticky?", pick: 1 },
    { text: "What's the most emo?", pick: 1 },
    { text: "How am I maintaining my relationship status?", pick: 1 },
    { text: "Example Card: _.", pick: 1 },
    { text: "After the earthquake, Sean Penn brought _ to the people of Haiti.", pick: 1 },
    { text: "In L.A. County Jail, word is you can trade 200 cigarettes for _.", pick: 1 },
    { text: "Maybe she's born with it. Maybe it's _.", pick: 1 },
    { text: "Life for American Indians was forever changed when the White Man introduced them to _.", pick: 1 },
    { text: "Next on ESPN2: The World Series of _.", pick: 1 },
    { text: "Step 1: _. Step 2: _. Step 3: Profit.", pick: 2 },
    { text: "Here is the church. Here is the steeple. Open the doors and there is _.", pick: 1 },
    { text: "How did I lose my virginity?", pick: 1 },
    { text: "During his midlife crisis, my dad got really into _.", pick: 1 },
    { text: "When I was a kid, we used to play Cowboys and _.", pick: 1 },
    { text: "My gym teacher got fired for adding _ to the obstacle course.", pick: 1 },
    { text: "Today on Maury: 'Help! My son is _!'", pick: 1 },
    { text: "Michelle Obama decided to ban _ from school lunches.", pick: 1 },
    { text: "In Michael Jackson's final moments, he thought about _.", pick: 1 },
    { text: "White people like _.", pick: 1 },
    { text: "Why is the ground moving?", pick: 1 },
    { text: "Rumor has it that Vladimir Putin's favorite dish is _ stuffed with _.", pick: 2 },
    { text: "I never truly understood _ until I encountered _.", pick: 2 },
    { text: "That's right, I killed _. How, you ask? _.", pick: 2 },
    { text: "Lifetime® presents '_, the Story of _.'", pick: 2 },
    { text: "Make a haiku.", pick: 3 },
    { text: "In M. Night Shyamalan's new movie, Bruce Willis discovers that _ had really been _ all along.", pick: 2 },
    { text: "_ is a slippery slope that leads to _.", pick: 2 },
    { text: "In a world ravaged by _, our only solace is _.", pick: 2 },
    { text: "That's right, I killed _. How, you ask? _.", pick: 2 },
    { text: "When I was tripping on acid, _ turned into _.", pick: 2 },
    { text: "_ + _ = _.", pick: 3 },
    { text: "What's the next superhero/sidekick duo?", pick: 2 },
    { text: "Dear Abby,\n\nI'm having some trouble with _ and would like your advice.", pick: 1 },
    { text: "After the earthquake, Sean Penn brought _ to the people of Haiti.", pick: 1 },
    { text: "In L.A. County Jail, word is you can trade 200 cigarettes for _.", pick: 1 },
    { text: "Maybe she's born with it. Maybe it's _.", pick: 1 },
    { text: "Life for American Indians was forever changed when the White Man introduced them to _.", pick: 1 },
    { text: "Next on ESPN2: The World Series of _.", pick: 1 },
    { text: "Step 1: _. Step 2: _. Step 3: Profit.", pick: 2 },
    { text: "Here is the church. Here is the steeple. Open the doors and there is _.", pick: 1 },
    { text: "How did I lose my virginity?", pick: 1 },
    { text: "During his midlife crisis, my dad got really into _.", pick: 1 },
    { text: "When I was a kid, we used to play Cowboys and _.", pick: 1 },
    { text: "My gym teacher got fired for adding _ to the obstacle course.", pick: 1 },
    { text: "Today on Maury: 'Help! My son is _!'", pick: 1 },
    { text: "Michelle Obama decided to ban _ from school lunches.", pick: 1 },
    { text: "In Michael Jackson's final moments, he thought about _.", pick: 1 },

    // Add more to reach 125
    { text: "Why am I covered in blood?", pick: 1 },
    { text: "What's the most common turn-on?", pick: 1 },
    { text: "What makes me feel young again?", pick: 1 },
    { text: "Who stole the cookies from the cookie jar?", pick: 1 },
    { text: "What is the meaning of life?", pick: 1 },
    { text: "The Smithsonian Museum of Natural History has just opened an interactive exhibit on _.", pick: 1 },
    { text: "It's a trap!", pick: 1 },
    { text: "I do not know with what weapons World War III will be fought, but World War IV will be fought with _.", pick: 1 },
    { text: "When I am a billionaire, I shall erect a 50-foot statue to commemorate _.", pick: 1 },
    { text: "What's the new fad diet?", pick: 1 },
    { text: "When I am President of the United States, I will create the Department of _.", pick: 1 },
    { text: "What will always get you laid?", pick: 1 },
    { text: "What's the most emo?", pick: 1 },
    { text: "What's the crustiest?", pick: 1 },
    { text: "What's the most common turn-on?", pick: 1 },
    { text: "What makes me feel young again?", pick: 1 },
    { text: "Who stole the cookies from the cookie jar?", pick: 1 },
    { text: "What is the meaning of life?", pick: 1 },
    { text: "The Smithsonian Museum of Natural History has just opened an interactive exhibit on _.", pick: 1 },
    { text: "It's a trap!", pick: 1 },
    { text: "I do not know with what weapons World War III will be fought, but World War IV will be fought with _.", pick: 1 },
    { text: "What's the new fad diet?", pick: 1 },
    { text: "When I am President of the United States, I will create the Department of _.", pick: 1 },
    { text: "What will always get you laid?", pick: 1 },
    { text: "What's the most emo?", pick: 1 },
    { text: "My life is ruled by a vicious cycle of _ and _.", pick: 2 },
    { text: "What's the next Happy Meal® toy?", pick: 1 },
    { text: "What's the one thing that can't be explained by science?", pick: 1 },
    { text: "Whatever you do, don't mention _.", pick: 1 },
    { text: "When I am President, I will create the Department of _.", pick: 1 },
    { text: "When Pharaoh remained unmoved, Moses called down a Plague of _.", pick: 1 },
    { text: "When the Big One hits, I hope I'm _.", pick: 1 },
    { text: "Where does the babies come from?", pick: 1 },
    { text: "While the United States raced the Soviet Union to the moon, the Mexican government funneled millions of pesos into research on _.", pick: 1 },
    { text: "White people like _.", pick: 1 },
    { text: "Who is this \"Rorschach\" guy and why does he paint so many pictures of _?", pick: 1 },
    { text: "Who stole the cookies from the cookie jar?", pick: 1 },
    { text: "Why am I sticky?", pick: 1 },
    { text: "Why can't I sleep at night?", pick: 1 },
    { text: "Why do I hurt?", pick: 1 },
    { text: "_: Good to the last drop.", pick: 1 },
    { text: "_: Kid-tested, mother-approved.", pick: 1 },
    { text: "_? There's an app for that.", pick: 1 },
    { text: "Action stations! Action stations! Set condition one throughout the fleet and brace for _!", pick: 1 },
    { text: "After months of controversy, the mayor finally decided that _ was in fact synonymous with _.", pick: 2 },
    { text: "After the earthquake, Sean Penn brought _ to the people of Haiti.", pick: 1 },
    { text: "Alcoholic games of Clue.", pick: 1 },
    { text: "Alternative medicine is now embracing the curative powers of _.", pick: 1 },
    { text: "And the Academy Award for Best Picture goes to _.", pick: 1 },
    { text: "And what did you bring for show and tell?", pick: 1 },
    { text: "Anna Nicole Smith.", pick: 1 },
    { text: "As the mom of five rambunctious boys, I'm no stranger to _.", pick: 1 },
    { text: "Betcha can't have just one!", pick: 1 },
    { text: "BILLY MAYS HERE FOR _.", pick: 1 },
    { text: "But before I kill you, Mr. Bond, I must show you _.", pick: 1 },
    { text: "Call the neighbors! I found _.", pick: 1 },
    { text: "Charades was ruined for me forever when my mom had to act out _.", pick: 1 },
    { text: "Click Here for _!", pick: 1 },
    { text: "Coming to Broadway this season, _: The Musical.", pick: 1 },
    { text: "Daddy, why is mommy crying?", pick: 1 },
    { text: "Dear Abby,\n\nI'm having some trouble with _ and would like your advice.", pick: 1 },
    { text: "During his midlife crisis, my dad got really into _.", pick: 1 },
    { text: "During sex, I like to think about _.", pick: 1 },
    { text: "Every Christmas, my uncle gets drunk and tells the story about _.", pick: 1 },
    { text: "Everyone down on the ground! We don't want to hurt anyone. We just want _!", pick: 1 },
    { text: "Finally! A service that delivers _ right to your door.", pick: 1 },
    { text: "For my next trick, I will pull _ out of _.", pick: 2 },
    { text: "Fun tip! When your man gets horny, try _.", pick: 1 },
    { text: "Getting married, having a few kids, buying some stuff, retiring to Florida, and dying.", pick: 1 },
    { text: "Give me liberty, or give me _!", pick: 1 },
    { text: "Gone with the Wind.", pick: 1 },
    { text: "He who controls _ controls the world.", pick: 1 },
    { text: "Hey baby, come back to my place and I'll show you _.", pick: 1 },
    { text: "Hey guys, welcome to Chili's! Would you like to start the night off with a round of _?", pick: 1 },
    { text: "How am I maintaining my relationship status?", pick: 1 },
    { text: "How did I lose my virginity?", pick: 1 },
    { text: "I do not know with what weapons World War III will be fought, but World War IV will be fought with _.", pick: 1 },
    { text: "I drink to forget _.", pick: 1 }
];
